# Path: installer.sh
adb install Aur*.apk
adb install Boo*.apk
adb install Dro*.apk
adb install Fal*.apk
adb install Fir*.apk
adb install Flu*.apk
adb install Gal*.apk
adb install Hid*.apk
adb install HiP*.apk
adb install Lig*.apk
adb install Off*.apk
adb install Pow*.apk
adb install Pro*.apk
adb install SMS*.apk
adb install Sol*.apk
adb install Spe*.apk
adb install Spo*.apk
adb install Swi*.apk
adb install Tor*.apk
adb install Van*.apk
adb install VLC*.apk
adb install xMa*.apk
adb install YMu*.apk
adb install ZLi*.apk
adb install नोव*.apk