# Path: installer.sh
adb install Applics/Aur*.apk
adb install Applics/Boo*.apk
adb install Applics/Dro*.apk
adb install Applics/Fal*.apk
adb install Applics/Fir*.apk
adb install Applics/Flu*.apk
adb install Applics/Gal*.apk
adb install Applics/Hid*.apk
adb install Applics/HiP*.apk
adb install Applics/Lig*.apk
adb install Applics/Off*.apk
adb install Applics/Pow*.apk
adb install Applics/Pro*.apk
adb install Applics/SMS*.apk
adb install Applics/Sol*.apk
adb install Applics/Spe*.apk
adb install Applics/Spo*.apk
adb install Applics/Swi*.apk
adb install Applics/Tor*.apk
adb install Applics/Van*.apk
adb install Applics/VLC*.apk
adb install Applics/xMa*.apk
adb install Applics/YMu*.apk
adb install Applics/ZLi*.apk
adb install Applics/नोव*.apk